### ISSUE TITLE
actividad 7 linea del tiempo evelyn santiago vitoria 

### ISSUE THREAD

**Issue by EvelynSantiagoVic** [SistemasTecTlaxiaco/actividad-7-EvelynSantiagoVic#1]
[linea del tiempo_ evelyn santiago victoria.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-EvelynSantiagoVic/files/9806313/linea.del.tiempo_.evelyn.santiago.victoria.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
tiene 18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
